# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.IntegerField(default=0)),
                ('sepal_width', models.IntegerField(default=0)),
                ('petal_length', models.IntegerField(default=0)),
                ('prediction', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
